#!/bin/sh
# Copyright (C) 2009-2014 nomadnt.com

. /lib/functions.sh

[ $ACTION == 'ifup' ] && {
	config_load network
	config_get proto $INTERFACE proto none
	
	[ $proto == 'batadv' ] && {
		config_get mesh $INTERFACE mesh bat0
		config_clear
		config_load batman-adv
		
		config_get network_coding $mesh network_coding 0
		[ $network_coding -eq 1 ] && {
			# Changing the mtu from 1524 to 1546
			ip link set dev $INTERFACE promisc on
			ip link set dev $INTERFACE mtu 1546
		}
	}
}
