#!/bin/sh /etc/rc.common
# Copyright (C) 2009-2014 nomadnt.com

START=15
STOP=90

. /lib/meos.sh

start(){
	[ "$(uci_get system @system[0] role 2> /dev/null)" == "A" ] && {
		logger -s -t "MeOS" "Detecting node role on $INTERFACE_WAN..."
		udhcpc -i $(meos_default_wan) -t 5 -qn -s /usr/share/udhcpc/meos.script
	}
	
	# Reloading configuration
	logger -s -t "MeOS" "Checking configuration"
	[ -d /lib/meos ] && for script in /lib/meos/*; do $script; done

	service_start /sbin/meos
}

stop(){
	logger -s -t "MeOS" "Shutdown MeOS services"
	service_stop /sbin/meos
}
