#!/bin/sh
# Copyright (C) 2009-2014 nomadnt.com

[ $DEBUG ] || . /lib/meos.sh

config_cb(){
	local _type="$1"
	local _cfg="$2"
	
	echo $_type | grep -qsE "^(led|button)$" && uci_remove system $_cfg
}

config_system(){
	local cfg="$1"
	local hostname timezone password role
	config_get hostname $cfg hostname "meos"
	config_get timezone $cfg timezone "UTC-2"
	config_get password $cfg password

	sys_hostname "$hostname"
	sys_timezone "$timezone"
	[ -n "$password" ] && {
		sys_user_passwd "root" "$password" 
		uci_remove system $cfg password
	}
}

# Configuring system
config_load system
config_foreach config_system system
uci_commit system
config_clear
