#!/bin/sh
# Copyright (C) 2009-2014 nomadnt.com

[ $DEBUG ] || . /lib/meos.sh

[ "$(uci_get system @system[0] role A)" = "A" ] && {
	uci_set dhcp @dnsmasq[0] authoritative 0
	uci_set dhcp @dnsmasq[0] rebind_protection 0
	
	for net in wan mesh lan; do
		uci_get dhcp $net > /dev/null || uci_add dhcp dhcp $net
	done
	
	uci_set dhcp wan interface "wan"
	uci_set dhcp wan ignore 1
	
	uci_set dhcp lan interface "lan"
	uci_set dhcp lan ignore 0
	uci_set dhcp lan start 20
	uci_set dhcp lan limit 200
	uci_set dhcp lan leasetime "12h"
	
	uci_set dhcp mesh interface "mesh"
	case "$(sys_role)" in
		G)
			config_load network
			config_get ipaddr mesh ipaddr
			config_clear

			uci_set dhcp mesh ignore 0
			uci_set dhcp mesh start "$(($(ip4addr2int $ipaddr) + 20))"
			uci_set dhcp mesh limit 200
			uci_set dhcp mesh leasetime "6h"
			;;
		B)
			uci_set dhcp mesh ignore 1
			;;
	esac

	uci_commit dhcp
}
