#!/bin/sh
# Copyright (C) 2009-2014 nomadnt.com

# simple url: http://speedtest.qsc.de/1MB.qsc

cURL="curl -s -w "%{speed_download}\\n" -o /dev/null"

usage(){
	echo "Usage: ${0##*/} [-h] [-s 1|5|10|100]" 1>&2; exit 1
}

while getopts "s:h" opt; do
	case "$opt" in
		h) HUMAN=1 ;;
		s) SIZE=$OPTARG ;;
		*) usage ;;
	esac
done

URL="http://speedtest.qsc.de/${SIZE:-1}MB.qsc"
SPEED=$($cURL --progress-bar --url $URL | sed 's/,/./g' || echo 0.000)

if [ ${HUMAN:-0} -eq 1 ]; then
	echo $SPEED | awk '{
		f = "BKMGTEPYZ"; s = ($0 * 8); 
		while(s >= 1024){s /= 1024; f = substr(f, 2);}
		printf("%.2f %sbps\n", s, substr(f, 1, 1))
	}'
else
	echo $SPEED | awk '{printf("%.2f\n", ($0 * 8))}'
fi
