#!/bin/sh

if [ "$BATTYPE" = "gw" ]; then
	case "$BATACTION" in
		add|del) ;;
		change)
			kill -SIGUSR2 $(cat /var/run/udhcpc-br-mesh.pid)
			kill -SIGUSR1 $(cat /var/run/udhcpc-br-mesh.pid) 
			;;
	esac
fi